package com.fanfan.novel.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fanfan.novel.model.ChatMessageBean;
import com.fanfan.novel.model.FaceAuth;
import com.fanfan.novel.model.NavigationBean;
import com.fanfan.novel.model.SiteBean;
import com.fanfan.novel.model.VideoBean;
import com.fanfan.novel.model.VoiceBean;
import com.fanfan.robot.model.CheckIn;
import com.fanfan.robot.model.Dance;
import com.fanfan.robot.model.Music;

import com.fanfan.novel.db.ChatMessageBeanDao;
import com.fanfan.novel.db.FaceAuthDao;
import com.fanfan.novel.db.NavigationBeanDao;
import com.fanfan.novel.db.SiteBeanDao;
import com.fanfan.novel.db.VideoBeanDao;
import com.fanfan.novel.db.VoiceBeanDao;
import com.fanfan.novel.db.CheckInDao;
import com.fanfan.novel.db.DanceDao;
import com.fanfan.novel.db.MusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageBeanDaoConfig;
    private final DaoConfig faceAuthDaoConfig;
    private final DaoConfig navigationBeanDaoConfig;
    private final DaoConfig siteBeanDaoConfig;
    private final DaoConfig videoBeanDaoConfig;
    private final DaoConfig voiceBeanDaoConfig;
    private final DaoConfig checkInDaoConfig;
    private final DaoConfig danceDaoConfig;
    private final DaoConfig musicDaoConfig;

    private final ChatMessageBeanDao chatMessageBeanDao;
    private final FaceAuthDao faceAuthDao;
    private final NavigationBeanDao navigationBeanDao;
    private final SiteBeanDao siteBeanDao;
    private final VideoBeanDao videoBeanDao;
    private final VoiceBeanDao voiceBeanDao;
    private final CheckInDao checkInDao;
    private final DanceDao danceDao;
    private final MusicDao musicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageBeanDaoConfig = daoConfigMap.get(ChatMessageBeanDao.class).clone();
        chatMessageBeanDaoConfig.initIdentityScope(type);

        faceAuthDaoConfig = daoConfigMap.get(FaceAuthDao.class).clone();
        faceAuthDaoConfig.initIdentityScope(type);

        navigationBeanDaoConfig = daoConfigMap.get(NavigationBeanDao.class).clone();
        navigationBeanDaoConfig.initIdentityScope(type);

        siteBeanDaoConfig = daoConfigMap.get(SiteBeanDao.class).clone();
        siteBeanDaoConfig.initIdentityScope(type);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        voiceBeanDaoConfig = daoConfigMap.get(VoiceBeanDao.class).clone();
        voiceBeanDaoConfig.initIdentityScope(type);

        checkInDaoConfig = daoConfigMap.get(CheckInDao.class).clone();
        checkInDaoConfig.initIdentityScope(type);

        danceDaoConfig = daoConfigMap.get(DanceDao.class).clone();
        danceDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        chatMessageBeanDao = new ChatMessageBeanDao(chatMessageBeanDaoConfig, this);
        faceAuthDao = new FaceAuthDao(faceAuthDaoConfig, this);
        navigationBeanDao = new NavigationBeanDao(navigationBeanDaoConfig, this);
        siteBeanDao = new SiteBeanDao(siteBeanDaoConfig, this);
        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);
        voiceBeanDao = new VoiceBeanDao(voiceBeanDaoConfig, this);
        checkInDao = new CheckInDao(checkInDaoConfig, this);
        danceDao = new DanceDao(danceDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);

        registerDao(ChatMessageBean.class, chatMessageBeanDao);
        registerDao(FaceAuth.class, faceAuthDao);
        registerDao(NavigationBean.class, navigationBeanDao);
        registerDao(SiteBean.class, siteBeanDao);
        registerDao(VideoBean.class, videoBeanDao);
        registerDao(VoiceBean.class, voiceBeanDao);
        registerDao(CheckIn.class, checkInDao);
        registerDao(Dance.class, danceDao);
        registerDao(Music.class, musicDao);
    }
    
    public void clear() {
        chatMessageBeanDaoConfig.clearIdentityScope();
        faceAuthDaoConfig.clearIdentityScope();
        navigationBeanDaoConfig.clearIdentityScope();
        siteBeanDaoConfig.clearIdentityScope();
        videoBeanDaoConfig.clearIdentityScope();
        voiceBeanDaoConfig.clearIdentityScope();
        checkInDaoConfig.clearIdentityScope();
        danceDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
    }

    public ChatMessageBeanDao getChatMessageBeanDao() {
        return chatMessageBeanDao;
    }

    public FaceAuthDao getFaceAuthDao() {
        return faceAuthDao;
    }

    public NavigationBeanDao getNavigationBeanDao() {
        return navigationBeanDao;
    }

    public SiteBeanDao getSiteBeanDao() {
        return siteBeanDao;
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

    public VoiceBeanDao getVoiceBeanDao() {
        return voiceBeanDao;
    }

    public CheckInDao getCheckInDao() {
        return checkInDao;
    }

    public DanceDao getDanceDao() {
        return danceDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

}
